# Generated by Django 3.2.6 on 2021-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
                ('design', models.BooleanField(default=False)),
                ('installation', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('hardscaping', models.BooleanField(default=False)),
                ('sod', models.BooleanField(default=False)),
                ('leaf_removal', models.BooleanField(default=False)),
                ('pots', models.BooleanField(default=False)),
            ],
        ),
    ]
