# Generated by Django 3.2.6 on 2021-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlcapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
